# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-03 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to='relationships.Author')),
                ('author_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='relationships.Author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(related_name='follower', through='relationships.Contact', to='relationships.Author'),
        ),
    ]
